# -*- coding: utf-8 -*-
"""data_prep/prepare_cifar10_drift.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

import torch, numpy as np
from torchvision import datasets, transforms

t_tensor = transforms.ToTensor()

def get_warmup_loader(batch=128, limit=4096):
    ds = datasets.CIFAR10(root='./data', train=True, download=True, transform=t_tensor)
    idx = list(range(min(limit, len(ds))))
    return torch.utils.data.DataLoader(torch.utils.data.Subset(ds, idx), batch_size=batch, shuffle=True, drop_last=True)

def _contrast(c):
    return transforms.Compose([transforms.ColorJitter(contrast=c), transforms.ToTensor()])

def stream(batch=128, total=50000, device='cpu'):
    base = datasets.CIFAR10(root='./data', train=True, download=True)
    X, y = np.array(base.data), np.array(base.targets)
    idx = np.random.permutation(len(X))[:total]
    X, y = X[idx], y[idx]

    cycle = [(0,1,2,3,4), (5,6,7,8,9), (0,2,4,6,8), (1,3,5,7,9)]
    for i in range(0, total, batch):
        phase = (i // 10000) % len(cycle)
        heavy = set(cycle[phase])
        c = 0.6 if phase % 2 == 0 else 1.4
        T = _contrast(c)

        sel = []
        ptr = i
        while len(sel) < min(batch, total - i):
            if (y[ptr] in heavy) or (np.random.rand() < 0.25):
                sel.append(ptr)
            ptr += 1
            if ptr >= i + batch: break

        imgs = torch.stack([T(transforms.ToPILImage()(X[j])) for j in sel])
        lbls = torch.tensor(y[sel], dtype=torch.long)
        yield imgs.to(device), lbls.to(device)