# -*- coding: utf-8 -*-
"""data_prep/prepare_rotmnist.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

import torch, numpy as np
from torchvision import datasets, transforms

def _rotator(angle):
    return transforms.Compose([
        transforms.RandomRotation((angle, angle)),
        transforms.ToTensor()
    ])

def get_warmup_loader(batch=128, limit=2048):
    t = transforms.ToTensor()
    ds = datasets.MNIST(root='./data', train=True, download=True, transform=t)
    idx = list(range(min(limit, len(ds))))
    return torch.utils.data.DataLoader(torch.utils.data.Subset(ds, idx), batch_size=batch, shuffle=True, drop_last=True)

def stream(batch=128, total=50000, step_deg=10, device='cpu'):
    raw = datasets.MNIST(root='./data', train=True, download=True)
    X, y = raw.data.numpy(), raw.targets.numpy()
    idx = np.random.permutation(len(X))[:total]
    X, y = X[idx], y[idx]

    for i in range(0, total, batch):
        angle = ((i // 5000) * step_deg) % 180
        t = _rotator(angle)
        imgs = torch.stack([t(transforms.ToPILImage()(x)) for x in X[i:i+batch]])
        lbls = torch.from_numpy(y[i:i+batch])
        yield imgs.to(device), lbls.to(device)
