# -*- coding: utf-8 -*-
"""data_prep/prepare_electricity.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

from river.datasets import Elec2
import numpy as np

def load_electricity(limit=None):
    ds = Elec2()
    Xs, ys = [], []
    for i, (x, y) in enumerate(ds):
        if limit and i >= limit: break
        Xs.append([float(v) for v in x.values()])
        ys.append(int(y))  # UP->1, DOWN->0 (river maps to 0/1)
    return np.array(Xs, float), np.array(ys, int)
