# -*- coding: utf-8 -*-
"""data_prep/prepare_sea.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

from river.datasets.synth import SEA
import numpy as np

def load_sea(n_samples=60000, noise=0.1, seed=42):
    gen = SEA(seed=seed)
    Xs, ys = [], []
    funcs = [0, 1, 2, 3]
    for i in range(n_samples):
        gen.variant = funcs[(i // 15000) % 4]
        x, y = gen.next()
        if np.random.rand() < noise:
            y = 1 - y
        Xs.append([x['att1'], x['att2'], x['att3']])
        ys.append(y)
    return np.array(Xs, float), np.array(ys, int)