# -*- coding: utf-8 -*-
"""sadel/bandit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

import numpy as np

class LinUCBBandit:
    """
    Per-class linear contextual bandit with UCB.
    Actions: -1 (dec), 0 (hold), +1 (inc) for threshold τ_c.
    """
    def __init__(self, d, alpha=0.5, lam=1.0, discount=0.98):
        self.d = d
        self.alpha = alpha
        self.lam = lam
        self.discount = discount
        self.A = lam * np.eye(d + 3)      # +3 for one-hot action
        self.A_inv = np.linalg.inv(self.A)
        self.b = np.zeros((d + 3,))
        self.theta = np.zeros((d + 3,))

    def _phi(self, context, action):
        a_vec = np.zeros(3); a_vec[action+1] = 1.0
        return np.concatenate([context, a_vec])

    def choose(self, context):
        ctx = np.asarray(context, float)
        scores = []
        for a in (-1, 0, +1):
            phi = self._phi(ctx, a)
            mean = phi @ self.theta
            var  = np.sqrt(max(1e-9, phi @ self.A_inv @ phi))
            scores.append((mean + self.alpha * var, a))
        scores.sort(reverse=True, key=lambda x: x[0])
        return scores[0][1]

    def update(self, context, action, reward):
        ctx = np.asarray(context, float)
        phi = self._phi(ctx, action)

        # discounted recursive inverse (Woodbury)
        delta = self.discount
        Ainv_u = self.A_inv @ phi
        denom = delta + phi @ Ainv_u
        self.A_inv = (1.0/delta) * (self.A_inv - np.outer(Ainv_u, Ainv_u) / max(1e-9, denom))

        self.b = self.discount * self.b + reward * phi
        self.theta = self.A_inv @ self.b