# -*- coding: utf-8 -*-
"""sadel/metrics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def ece(probs, labels, n_bins=10):
    probs = np.asarray(probs, float)
    labels = np.asarray(labels, int).ravel()
    confid = probs.max(axis=1)
    preds = probs.argmax(axis=1)
    bins = np.linspace(0, 1, n_bins+1)
    e = 0.0
    N = len(labels)
    for i in range(n_bins):
        lo, hi = bins[i], bins[i+1]
        mask = (confid >= lo) & (confid < hi if i < n_bins-1 else confid <= hi)
        if mask.any():
            acc = (preds[mask] == labels[mask]).mean()
            conf = confid[mask].mean()
            e += (mask.sum() / N) * abs(acc - conf)
    return float(e)

def acc_f1(probs, labels):
    labels = np.asarray(labels, int).ravel()
    preds = np.asarray(probs).argmax(axis=1)
    return accuracy_score(labels, preds), f1_score(labels, preds, average='macro')