# -*- coding: utf-8 -*-
"""sadel/model_zoo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

import torch, torch.nn as nn

class SmallCNN(nn.Module):
    def __init__(self, in_ch=1, n_classes=10):
        super().__init__()
        spatial = 7 if in_ch == 1 else 8
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(64 * spatial * spatial, 128), nn.ReLU(),
            nn.Linear(128, n_classes)
        )

    def forward(self, x):
        return self.net(x)

@torch.no_grad()
def torch_predict_proba(model, x, device):
    model.eval()
    logits = model(x.to(device)).cpu()
    z = logits - logits.max(dim=1, keepdim=True).values
    e = torch.exp(z)
    p = e / e.sum(dim=1, keepdim=True)
    return p.numpy()
