# -*- coding: utf-8 -*-
"""sadel/utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

import numpy as np
import torch, torch.nn as nn
from collections import deque

class RollingStat:
    def __init__(self, window=500):
        self.buf = deque(maxlen=int(window))
    def add(self, v): self.buf.append(float(v))
    def mean(self):
        return float(np.mean(self.buf)) if self.buf else 0.0

def train_step(model, xb, yb, opt, device):
    model.train()
    opt.zero_grad()
    loss = nn.CrossEntropyLoss()(model(xb.to(device)), yb.to(device))
    loss.backward()
    opt.step()
    return float(loss.item())