# -*- coding: utf-8 -*-
"""sadel/controller.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

import numpy as np

class BudgetController:
    """
    Policy-regularized budget controller.
    Selects binary activation vector under soft budget B (sum(cost * prob) <= B).
    """
    def __init__(self, costs, lambda_b=0.5, lambda_p=0.3):
        self.costs = np.asarray(costs, float)
        self.lb = float(lambda_b)
        self.lp = float(lambda_p)
        self.prev = np.zeros_like(self.costs)

    def step(self, gains, B):
        gains = np.asarray(gains, float).ravel()
        # logistic gating with penalties
        z = gains - self.lb * self.costs - self.lp * self.prev
        prob = 1.0 / (1.0 + np.exp(-z))

        # scale to respect budget
        total = float((prob * self.costs).sum())
        if total > B and total > 1e-9:
            prob *= (B / total)

        a = (prob >= 0.5).astype(float)
        # if nothing selected, force best
        if a.sum() == 0:
            a[np.argmax(gains)] = 1.0
        self.prev = a
        return a.nonzero()[0].tolist(), a
