# -*- coding: utf-8 -*-
"""sadel/pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqlnLv58f0JglX3Smb64PMnLiS7YMbET
"""

import numpy as np
from .bandit import LinUCBBandit
from .controller import BudgetController
from .safety import SafetyGate
from .metrics import acc_f1, ece

class SADEL:
    """
    Minimal SA-DEL glue:
    - maintain per-class bandits to adjust thresholds τ_c
    - gate models under a soft compute/energy budget
    """
    def __init__(self, n_classes, n_models, model_costs,
                 bandit_dim=5, alpha=0.5, lam=1.0, discount=0.98,
                 lambda_b=0.5, lambda_p=0.3,
                 safety_eps=0.02, tau_step=0.05):
        self.C = int(n_classes)
        self.K = int(n_models)
        self.bandits = [LinUCBBandit(d=bandit_dim, alpha=alpha, lam=lam, discount=discount)
                        for _ in range(self.C)]
        self.tau = np.full((self.C,), 0.5)
        self.controller = BudgetController(model_costs, lambda_b=lambda_b, lambda_p=lambda_p)
        self.safety = SafetyGate(acc_baseline=0.0, eps=safety_eps, d_tau=tau_step)

    def class_context(self, acc, cal, diversity, drift, cost_norm):
        # pack 5 dims -> bandit_dim
        return np.array([acc, cal, diversity, drift, cost_norm], float)

    def update_thresholds(self, class_stats, rewards):
        # class_stats[c] -> (acc, ece, diversity, drift, cost_norm)
        for c in range(self.C):
            ctx = self.class_context(*class_stats[c])
            action = self.bandits[c].choose(ctx)
            delta = {-1:-0.05, 0:0.0, +1:0.05}[action]
            self.tau[c] = self.safety.clip_tau(self.tau[c], delta)
            self.bandits[c].update(ctx, action, rewards[c])

    def select_models(self, per_model_competence, budget):
        """
        per_model_competence: (K,B) or (K,) competence scores.
        Returns (active_indices, binary_vector)
        """
        arr = np.asarray(per_model_competence, float)
        gains = arr.mean(axis=1) if arr.ndim == 2 else arr
        return self.controller.step(gains=gains, B=budget)

    def fuse(self, probs_k, active_idx):
        # probs_k: (K,B,C), fuse by mean over active models
        return probs_k[active_idx].mean(axis=0)

    def evaluate(self, probs, labels):
        acc, f1 = acc_f1(probs, labels)
        cal = ece(probs, labels)
        return acc, f1, cal
